site_name: Printout
site_description: Enhanced print function with automatic logging
repo_url: https://github.com/jenkinscode1/printout
repo_name: jenkinscode1/printout
edit_uri: ""

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [printout]  # Path to your package

nav:
  - Home: index.md
  - API Reference: api.md