name: Publish printout to PyPI

on:
  push:
    tags:
      - "v*"   # Run only on version tags like v0.1.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # 3. Install build tools
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      # 4. Build the package
      - name: Build package
        run: |
          python -m build

      # 5. Publish to PyPI
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.11
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}