name: Publish to PyPI

on:
  push:
    branches:
      - master  # or "tags: [v*]" if you only want tags

jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel twine
          pip install build

      - name: Clean old builds
        run: rm -rf dist build *.egg-info
        
      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.11
        with:
          user: __token__
          password: ${{ secrets.PYPIAPITOKEN }}