name: Publish to PyPI

on:
  push:
    branches:
      - master  # or "tags: [v*]" if you only want tags

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for Trusted Publishing
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade build setuptools wheel

      - name: Clean old artifacts
        run: |
          rm -rf build dist *.egg-info

      - name: Build package
        run: python -m build

      - name: Publish to PyPI with Trusted Publisher
        uses: pypa/gh-action-pypi-publish@release/v1